# This is a basic workflow to help you get started with Actions
name: Git_DevOps_Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]  

  pull_request_review_comment:
    id-token: write
    contents: read
    
  pull_request:
    branches: [ main ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# A workflow rn is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: gitzV/awss3Sync@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.	
        
  DEV:
    runs-on: ubuntu-latest
    environment: DEV
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ap-south-1                                           ## Put the region in github secret.
        role-to-assume: arn:aws:iam::446963233070:role/github-oidc-role  ## Put role arn in github secret.
        role-session-name: oidcRoleSession
        
    - name: test assume role
      run: aws sts get-caller-identity --region ap-south-1               ## Put the region in github secret.

    - name: Copy files to s3
      run: aws s3 sync . s3://mastekkelloggg/



    - name: Run Trigger
      run: |
        aws glue start-trigger --name Foo
        
    - name: Run stack
      run: |
        #aws cloudformation delete-stack  --stack-name devStack
        #aws cloudformation create-stack  --stack-name devStack --template-body file://GlueJobYml.yml 
        aws cloudformation create-stack  --stack-name devStack --template-body file://GlueJobYml.yml --parameters file://dev_stack_parameter.json         
        aws glue start-trigger --name Foo
